### PR TITLE
Update to 0.9.9 and refresh README

### LINKED ISSUE #1: Update to 0.9.5?
Looks like there's a newer and more awesome release upstream. 

https://github.com/babluboy/bookworm/releases 

@BharatKalluri @babluboy do you plan on doing an update here?

### PR DESCRIPTION
**Pull request by nedrichards**
Fixes #1

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
Ah, looks like the launch commands changed upstream

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
@babluboy so if you think that's all OK - feel free to merge this PR - that'll build and release automatically.

**Comment by babluboy** [comment]
@nedrichards yes the launch command was changed to the RDNN name to satisfy the AppCenter submission criteria....I have merged the PR...many thanks....

**Pull request merged**
